### ISSUE TITLE
Please provide an updated version of the SDK

### ISSUE THREAD

**Issue by savy-91** [paldesk/paldesk-ios-sdk#1]
Hi!
I recently became a paid customer and while trying to integrate your SDK in a new project I am facing this error:

module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1.2 compiler:

Can you please provide an updated version of your SDK compiled with an up to date compiler?

An alternative solution would be to provide the library compiled with the BUILD_LIBRARY_FOR_DISTRIBUTION option.

Thanks

**Comment by fmatijevic** [comment]
Hi!
As we spoke on our customer support, we will make this our priority very soon.
Thanks!

**Comment by diusenko** [comment]
the same problem.

**Comment by onlyonemj** [comment]
Any idea when a fix will be rolled out? We need an updated version ASAP

**Comment by fmatijevic** [comment]
We are currently working on this.
Updated version along with the new features is coming soon.

**Comment by onlyonemj** [comment]
Any estimation when a new version will be ready? Few days? A week?
Two weeks? We need to plan around this, I hope you understand. Thank you.

**Comment by fmatijevic** [comment]
New version should arrive at the end of the week.

**Comment by onlyonemj** [comment]
Fantastic, thanks for the update

**Comment by savy-91** [comment]
Hi @fmatijevic is this closed with fb1996f41697863bf6d348546ee42a99a129e9e1?

**Comment by fmatijevic** [comment]
Late answer, sorry.
Yes, it is.
