### ISSUE TITLE
Crash during chat

### ISSUE THREAD

**Issue by savy-91** [paldesk/paldesk-ios-sdk#4]
I created a new project from scratch where I basically just initialize Paldesk and then open a chat.

I manage to send a couple of quick messages from the app but then it crashes suddendly.

This happened compiling with XCode 11.12.1 and it happens both if I am using Paldesk inside Flutter as well as if I am creating a native Swift app.

Right now I only tried this using Cocoapods but I will try with Carthage as well, even though I don't believe that's the problem.

![Screenshot 2020-01-09 at 10 12 14](https://user-images.githubusercontent.com/6215122/72054389-2c397600-32c9-11ea-9178-59ad2518fc28.png)

EDIT: corrected XCode 11.12.1 version

**Comment by fmatijevic** [comment]
This shouldn't be related to Cocoapods.
We need more info about this as this may be related to your Paldesk iOs SDK configuration. Could you send me an email to support@paldesk.com with your Paldesk account email?
Thanks

**Comment by savy-91** [comment]
Done

**Comment by fmatijevic** [comment]
@savy-91 This is related to your Cocoapods. I can't reproduce this with official Carthage distribution. Thanks for helping us. We will do our best to hurry with Cocoapods integration.
